//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP
    {
        public APP()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.COSTUMERs = new HashSet<COSTUMER>();
        }
    
        public int ID_App { get; set; }
        public int ID_Developer { get; set; }
        public string Name { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual DEVELOPER DEVELOPER { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual ICollection<COSTUMER> COSTUMERs { get; set; }
    }
}
