//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.APP_PURCHASED = new HashSet<APP_PURCHASED>();
            this.COMMENTs = new HashSet<COMMENT>();
        }
    
        public int ID_Customer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_Membership { get; set; }
    
        public virtual ICollection<APP_PURCHASED> APP_PURCHASED { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual MEMBERSHIP MEMBERSHIP { get; set; }
    }
}
