//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSHIP
    {
        public MEMBERSHIP()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public int ID_Membership { get; set; }
        public System.DateTime LastPayment { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
